services:
  document-management-backend:
    container_name: document-management-backend
    build:
      context: ./document-management-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    # map a volume for the file uploads
    volumes:
      - ./.data/uploads:/usr/src/app/uploaded-file-data
    depends_on:
      - database
      - redis-setup
      - ingestion-service-backend
  ingestion-service-backend:
    container_name: ingestion-service-backend
    build:
      context: ./ingestion-service-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
      - redis-setup
  database:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./.data/db:/var/lib/postgresql/data

  redis-setup:
    container_name: redis
    build: ./redis-setup
    volumes:
      - ./.data/redis:/data
